# Generated by Django 3.2.9 on 2021-12-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
